import type { NextPage } from 'next'
import Head from 'next/head'
import { trpc } from 'src/utils/trpc'
import { customAlphabet } from 'nanoid'
import { useRouter } from 'next/router'

const nanoid = customAlphabet('wertyuiopasdfghjklzxcvbnm1234567890', 4)

const Home: NextPage = () => {
  const router = useRouter()
  function createRoom() {
    const roomId = nanoid()
    router.push(`/rooms/${roomId}`)
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mxuauto flex flex-col items-center justify-center h-screen p-4'>
        <h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700'>
          Create Chat Room
        </h1>
        <button onClick={() => createRoom()}>join room</button>
      </main>
    </>
  )
}

export default Home
